-- 사번, 이름, 부서번호, 부서이름 조회
SELECT * FROM TAB;

SELECT * FROM LOCATIONS l ;

SELECT * FROM EMPLOYEES e ;

SELECT * FROM DEPARTMENTS d ;

SELECT EMPLOYEE_ID, FIRST_NAME || '' || LAST_NAME NAME, DEPARTMENT_ID , DEPARTMENT_NAME 
FROM EMPLOYEES e 
JOIN DEPARTMENTS d USING(DEPARTMENT_ID);